document.addEventListener('DOMContentLoaded', () => {
  let booksData = [
    {
      "id": "1",
      "name": "День Триффидов",
      "author": "Джон Уиндум",
      "genre": "Классическая проза",
      "image": "./img/cat2_img16.jpg",
      "description":"«Если день начинается воскресной тишиной, а вы точно знаете, что сегодня среда, значит, что-то неладно». Однажды вечерней порой жители Лондона с интересом наблюдали необычное явление – зеленый звездный дождь, озаривший все небо. Наутро свидетели загадочного явления проснулись слепыми, а вскоре стало ясно, что зрения лишилось почти все население Земли. В мире грядут большие перемены. Те немногие, кто сумел сохранить зрение, получают почти безграничную власть и доступ к накопленным человечеством ресурсам. Но беда, как известно, не приходит одна – и в действие вступает третья сила: триффиды, разумные хищные растения, способные передвигаться и охотиться на людей. Сложная система безопасности, созданная для сдерживания очень ценных, но чрезвычайно опасных растений, дает сбой, и триффиды вырываются на свободу…",
      "language": "Ru",
      "free": "Да",
      "read": "Нет",
      "upload": "Нет",
      "cost": "0",
      "pdf":"https://drive.google.com/file/d/1BW1qO-JylIoAmpPYli8L-ZP0DWOvQjJ_/view?usp=drive_link"
    },
    {
        "id": "2",
        "name": "Мартин Иден",
        "author": "Джек Лондон",
        "genre": "Классическая проза",
        "image": "./img/cat2_img17.jpg",
        "description":"Роман, который взорвал сознание нескольких поколений молодых людей разных стран, одержимых его почти ницшеанской идеей «сильного мужчины», преодолевающего любые препятствия.",
        "language": "Ru",
        "free": "Да",
        "read": "Нет",
        "upload": "Нет",
        "cost": "0",
        "pdf":"https://drive.google.com/file/d/1WgsJT6cqr-8eTinDIh192ANMWV6lxHKr/view?usp=drive_link"
      },
      {
        "id": "3",
        "name": "Почему я не худею",
        "author": "Анастасия Томилова",
        "genre": "Здоровье и правильное питание",
        "image": "./img/cat2_img18.jpg",
        "description":"Психолог и психотерапевт Анастасия Томилова предлагает надежный способ, который поможет вырваться из замкнутого круга диет. Ее книга адресована всем мужчинам и женщинам, которые хотят наладить здоровые отношения с едой, восстановить пищевое поведение, разобраться в психологических особенностях, которые заставляют месяцами мучительно «улучшать себя», и освоить более эффективные способы корректировки и поддержания веса.",
        "language": "Ru",
        "free": "Да",
        "read": "Нет",
        "upload": "Нет",
        "cost": "0",
        "pdf":"https://drive.google.com/file/d/10trUwgxJU4esIfh71aikOSP8LjEtrQDu/view?usp=drive_link"
      },    
      {
        "id": "4",
        "name": "Сказать жизни - Да",
        "author": "Виктор Франкл",
        "genre": "Развитие",
        "image": "./img/cat2_img19.jpg",
        "description":"Эта удивительная книга сделала ее автора одним из величайших духовных учителей человечества в XX веке. В ней философ и психолог Виктор Франкл, прошедший нацистские лагеря смерти, открыл миллионам людей всего мира путь постижения смысла жизни. Дополнительный подарок для читателя настоящего издания – пьеса «Синхронизация в Биркенвальде», где выдающийся ученый раскрывает свою философию художественными средствами.",
        "language": "Ru",
        "free": "Да",
        "read": "Нет",
        "upload": "Нет",
        "cost": "0",
        "pdf":"https://drive.google.com/file/d/1qY9pPgDWEGkIi93LraesnPWi5fym4YpI/view?usp=drive_link"
      },    
      {
        "id": "5",
        "name": "Ты как, только често",
        "author": "Дженна Кутчер",
        "genre": "Классическая проза",
        "image": "./img/cat2_img20.jpg",
        "description":"Автор этой книги Дженна Кутчер не понаслышке знает, как люди с выгоранием пытаются держаться за привычные занятия и оставаться эффективными из последних сил. Поэтому она написала книгу для всех, кто хочет прислушаться к себе, научиться испытывать неподдельную радость и вспомнить о своих настоящих желаниях. Дженна говорит читателям: «Проснитесь, оглянитесь на свою жизнь и прислушайтесь к себе. Научитесь слышать свой собственный голос, ведь вы уже знаете ответы на все вопросы».",
        "language": "Ru",
        "free": "Да",
        "read": "Нет",
        "upload": "Нет",
        "cost": "0",
        "pdf":"https://drive.google.com/file/d/1t-i4FSXRgAQZ3s5NcV1CfCTwn4Ywj8la/view?usp=drive_link"
      },
      {
        "id": "6",
        "name": "Метро 2033",
        "author": "Дмитрий Глуховский",
        "genre": "Антиутопия, постапокалипсис, мутанты",
        "image": "./img/cat2_img10.jpg",
        "description":"«Метро 2033» – культовый роман-антиутопия, один из главных российских бестселлеров нулевых. Переведен на 37 иностранных языков, заинтересовал Голливуд, превращен в атмосферные компьютерные блокбастеры, породил целую книжную вселенную и настоящую молодежную субкультуру во всем мире.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1500",
        "pdf":"https://drive.google.com/file/d/1OVntSqOMAviyjCRvbFMqSA4EZceLDRfF/view?usp=drive_link"
      },
      {
        "id": "7",
        "name": "Мастер и Маргарита",
        "author": "ДМихаил Булгаков",
        "image": "./img/cat2_img8.jpg",
        "description":"«Мастер и Маргарита» – бесспорно лучшее произведение Булгакова. Это к тому же – итоговое его произведение по отношению ко всему, что он написал, как бы резюмирующее представления писателя о смысле жизни, о человеке, о его смертности и бессмертии, о борьбе доброго и злого начала в истории и в нравственном мире человека. Иллюстрации Аллы Марковской.",
        "genre": "Историческое фэнтези",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "500",
        "pdf":"https://drive.google.com/file/d/131I-pavoFvviiSBhX3zhxdrYFUCDRSAP/view?usp=drive_link"
      },
      {
        "id": "8",
        "name": "Думай медленно... Решай быстро",
        "author": "Даниэль Канеман",
        "genre": "Саморазвитие, Личностный рост",
        "image": "./img/cat2_img9.jpg",
        "description":"Наши действия и поступки определены нашими мыслями. Но всегда ли мы контролируем наше мышление? Нобелевский лауреат Даниэль Канеман объясняет, почему мы подчас совершаем нерациональные поступки и как мы принимаем неверные решения. У нас имеется две системы мышления. «Медленное» мышление включается, когда мы решаем задачу или выбираем товар в магазине. Обычно нам кажется, что мы уверенно контролируем эти процессы, но не будем забывать, что позади нашего сознания в фоновом режиме постоянно работает «быстрое» мышление – автоматическое, мгновенное и неосознаваемое…",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "800",
        "pdf":"https://drive.google.com/file/d/1mOHmuDL2jYWxP78XAsTp7LRmZC3xC8g4/view?usp=drive_link"
      },
      {
        "id": "9",
        "name": "Так говорил Заратустра",
        "author": "Фридрих Ницше",
        "genre": "Философская проза, трактаты",
        "image": "./img/cat2_img21.jpg",
        "description":"Трактат «Так говорил Заратустра» называют ницшеанской Библией. В нем сформулирована излюбленная идея Ницше – идея Сверхчеловека, который является для автора нравственным образцом, смыслом существования, тем, к чему нужно стремиться.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1500",
        "pdf":"https://drive.google.com/file/d/1O-OrXYvx4k4G74S18i3sPPCGYuqVp5MC/view?usp=drive_link"
      },
      {
        "id": "10",
        "name": "Не орите на меня",
        "author": "Игорь Романов",
        "genre": "Психологические тренинги",
        "image": "./img/cat2_img3.jpg",
        "description":"Выходить победителем из любой перепалки. Гасить конфликт парой фраз. Доброжелательно отстаивать свои границы и превращать врагов в хороших приятелей. Этому учит книга, написанная врачом-психиатром, психологом с тридцатилетним стажем, деканом факультета коммуникативного менеджмента РГСУ, бизнес-тренером Игорем Романовым. Он предлагает 8 проверенных техник, которые помогут свести на нет психологическую агрессию и дать возможность перейти к конструктивным переговорам.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1800",
        "pdf":"https://drive.google.com/file/d/1C-TgRS8udEwN4k2qioL1IhXJjEoWCm3m/view?usp=drive_link"
      },
      {
        "id": "11",
        "name": "Купи себе эти чёртовы лилии",
        "author": "Тара Шустер",
        "genre": "Зарубежная психологоя, Саморазвитие",
        "image": "./img/cat2_img4.jpg",
        "description":"«Купи себе эти чертовы лилии» – история о том, как автор этой книги, Тара Шустер, взяла ответственность за свою жизнь и стала «ниндзя любви к себе». Путь к ее взрослению был вымощен депрессией, тревогой и стыдом во многом благодаря несчастливому детству и недостатку родительской любви. Но однажды Тара твердо решила для себя: эмоциональные раны нужно лечить добротой.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1300",
        "pdf":"https://drive.google.com/file/d/1wbw_DMdGU65WuSYUL61w7Cd5ywP8rNyz/view?usp=drive_link"
      },
      {
        "id": "12",
        "name": "Секс. Все, что вы хотели узнать о сексе, но боялись спросить",
        "author": "Наталья Краснова",
        "genre": "Любовь и отношения, Секс-руководства",
        "image": "./img/cat2_img5.jpg",
        "description":"В этой книге ответы на 69 самых интересных вопросов про секс. И 69 полноценных ответов, которые опираются на исследования ученых (антропологов, эволюционных психологов, нейробиологов, гинекологов, андрологов и других «ологов»). Здесь 69 историй из жизни обычных людей, которые столкнулись с проблемами в сексуальной жизни. И решения этих проблем тоже здесь. Благодаря этой книге вы узнаете, что 15 сантиметров – это не мало, а даже больше среднестатистической вместимости женщины. Также узнаете, что три минуты фрикций – это в три раза больше нормы, установленной Международной ассоциацией сексуальной медицины (МАСМ). Есть глава про секс втроем. Про секс вдвоем тоже есть. И даже про секс в одного есть глава. Узнаете, что будет, если убрать секс из своей жизни (спойлер: ничего страшного). Определите свою половую конституцию и узнаете про своего партнера много интересного. Книга содержит нецензурную брань!",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1800",
        "pdf":"https://drive.google.com/file/d/13noNysnVd-wpTHZpSCqraaZrOfEB19E_/view?usp=drive_link"
      },
      {
        "id": "13",
        "name": "К себе нежно",
        "author": "Ольга Примаченко",
        "genre": "Саморазвитие, Личностный рост",
        "image": "./img/cat2_img6.jpg",
        "description":"Автор книги Ольга Примаченко – журналист, экс-главный редактор LADY.TUT.BY и автор блога Gnezdo.by – говорит с читателем о важном: о принятии своих чувств, желаний и тела, о расставлении приоритетов и границ, о создании питательного пространства вокруг себя, а также об экологичном взаимодействии с миром и людьми. В конце книги читателя ждет 31-дневная практика нежности к себе.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1400",
        "pdf":"https://drive.google.com/file/d/1FZRG5BCdRqMKHEe3SJkui--heiSjGaxz/view?usp=drive_link"
      },
      {
        "id": "14",
        "name": "И.Сталин Сочинения",
        "author": "И.Сталин",
        "genre": "Сочинения",
        "image": "./img/cat2_img7.jpg",
        "description":"Прижизненное издание. Сохранность комплекта хорошая. Печатается по постановлению Центрального комитета Всесоюзной коммунистической партии (большевиков).",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "700",
        "pdf":"https://drive.google.com/file/d/1Z-z2zY62NQXa6bDJSTT27e0PRN_rgtxc/view?usp=drive_link"
      },
      {
        "id": "15",
        "name": "Продавец обуви. История компании Nike",
        "author": "Фил Найт",
        "genre": "Биографии и мемуары, истории из бизнеса",
        "image": "./img/cat2_img12.jpg",
        "description":"Nike – один из самых узнаваемых мировых брендов. Создатель компании – Фил Найт – один из богатейших людей, хотя еще в юности он не мог себе позволить купить кроссовки Adidas. 50 лет назад студент Орегонского университета и бегун на средние дистанции Фил Найт занял у отца 50 баксов и начал перепродавать кроссовки из Японии. Сегодня годовой оборот компании Nike составляет 30 миллиардов долларов. А пара «найков» найдется в шкафу у каждого – от президента до подростка. Фил Найт – человек-загадка, он редко дает интервью. Эта книга – исповедь о создании компании, которой удалось подарить мечту миллионам людей.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1000",
        "pdf":"https://drive.google.com/file/d/1xt_2fu5NJk-c9XmnSNN9Qv1sQPGzFvar/view?usp=drive_link"
      },
      {
        "id": "16",
        "name": "Я тебя прощаю Как проработать семейные травмы и понять себя",
        "author": "Илсе Санд",
        "genre": "Зарубежная психологоя, Саморазвитие",
        "image": "./img/cat2_img14.jpg",
        "description":"Мой и личный и профессиональный опыт позволил мне обнаружить целительную силу метода, в котором сочетаются два элемента: особое видение своих родственников и доверительное общение, откровенный и искренний разговор с ними. Этот метод называется «психогенеалогическая терапия». Конечно, им могут пользоваться профессиональные психотерапевты, но в этой книге речь пойдет о том, как вы можете применять его, чтобы помочь самому себе с помощью своих родственников, но без их прямого участия. В этой книге она рассказывает, как с помощью инструментов психогенеалогической терапии проанализировать чувства и эмоции и помочь себе найти внутреннюю опору – даже если мамы, папы, бабушки или дедушки уже нет рядом. Написание писем от лица родственников, техника пустого стула, разговор с фотографией и другие практики помогут принять собственные чувства и получить поддержку близких – живых и покинувших этот мир, – чтобы излечить душевные раны.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1000",
        "pdf":"https://drive.google.com/file/d/1jkrtXiKO3oTY3qG-Mky1xjkUe1HaKwYR/view?usp=drive_link"
      },
      {
        "id": "17",
        "name": "Нет значит нет. Как перестать быть удобным и научиться говорить «нет» без угрызений совести",
        "author": "Деймон Захариадис",
        "genre": "Социальная психология, Саморазвитие",
        "image": "./img/cat2_img15.jpg",
        "description":"Отказ не делает вас плохим человеком. Наоборот, умение говорить «нет» – один из важнейших навыков, которым мы можем овладеть. Он повышает нашу эффективность, улучшает отношения с окружающими и наделяет спокойной уверенностью. И если вам надоело быть удобным и безотказным – эта книга для вас!",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "450",
        "pdf":"https://drive.google.com/file/d/1eHGgjrkPc2m92eV6JRQBgXmHKP6y9RJa/view?usp=drive_link"
      },
      {
        "id": "18",
        "name": "Дюна. Дом Атрейдесов",
        "author": "Брайан Герберт, Кевин Андерсон",
        "genre": "Боевая фантастика, Зарубежная фантастика",
        "image": "./img/cat2_img13.jpg",
        "description":"Первая книга цикла о событиях, предшествовавших основному действию «Дюны» Фрэнка Герберта, роман, в котором мы ступаем на планету Арракис за несколько десятилетий до того, как на нее ступит легендарный Пауль Муад’Диб. Юный герцог Лето Атрейдес прибывает на технократическую планету Икс, чтобы пройти годовой курс обучения, а планетолог Пардот Кинес ищет способ превратить пустынный Арракис в цветущий зеленый рай…",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1000",
        "pdf":"https://drive.google.com/file/d/1b7e5MMrzkpiwMfIvFr6x4dM_Po3N9ln3/view?usp=drive_link"
      },
      {
        "id": "19",
        "name": "Выживальщики 14. Диверсанты",
        "author": "Константин Денисов",
        "genre": "Боевая фантастика, Героическая фантастика",
        "image": "./img/cat2_img22.jpg",
        "description":"Противостояние с хозяевами планеты обостряется. Теперь на главных героев охотятся, понимая, что они стали слишком опасны. Но найти их не так просто, маленькой группе иногда проще ускользнуть, чем принять бой, хотя и от схватки они зачастую не бегают. Впереди развязка истории с Энергоном, и куда более близкий контакт с хозяевами планеты. Хватит ли сил, чтобы продолжить борьбу с таким мощным противником? Все ли выживут в этой войне? Обо всём этом в четырнадцатой книге Выживальщиков",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "500",
        "pdf":"https://drive.google.com/file/d/1QzzxtZ8Z2n6tK0AREthrJRjwqkmxyAak/view?usp=drive_link"
      },
      {
        "id": "20",
        "name": "Фактор дисбаланса",
        "author": "Макс Глебов",
        "genre": "Боевая фантастика, Боевое фэнтези",
        "image": "./img/cat2_img23.jpg",
        "description":"Договоренности с кибами и единственным выжившим тайкуном дают Сергею Белову множество новых возможностей, но при этом сильно растут и риски. С каждым днем его всё глубже затягивает в запутанный клубок интриг аристократов постапокалиптического мира, сложившегося на Земле после Чужой войны. Сергей вынужден скрывать свои истинные планы от всех участников этой жестокой игры. Даже от тех, кто уже является или ещё только может стать его друзьями.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1250",
        "pdf":"https://drive.google.com/file/d/187DLRFD2gwOKkJOOd85e89bmvYsDUG5D/view?usp=drive_link"
      },
      {
        "id": "21",
        "name": "Контуженный АДАПТАЦИЯ",
        "author": "Алекс Гор",
        "genre": "Боевая фантастика, Космическая фантастика",
        "image": "./img/cat2_img24.jpg",
        "description":"Космос безграничен и загадочен, сколько в нем ещё неизведанного. Джон Сол опять оказался на грани. Остаться самим собой или подвергнуться трансформе, выбор не прост. А возможно, что его и нет вовсе. Отсутствие звездных карт толкает группу выживших преступников на рискованный шаг - посещение единственной известной точки в пространстве, только вот цель пути оказалась совсем не такой, как ожидалось.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "400",
        "pdf":"https://drive.google.com/file/d/1dMU-4Om3gkOpYq_QonZzf_ysc-dmtR-f/view?usp=drive_link"
      },
      {
        "id": "22",
        "name": "Любовь со смертью",
        "author": "Ольга Гусейнова",
        "genre": "Любовное фэнтези, Попаданцы",
        "image": "./img/cat2_img25.jpg",
        "description":"Обряд на удачу может спасти от провала! Но кто же знал, что схитрить не получится и меня занесет в другой мир? Хочешь не хочешь, а начинается новая жизнь. Теперь я потомственная аристократка, которой предстоит решить множество проблем. Еще поступить в академию магии и встретить любовь. Ведь обрести счастье целители могут лишь по большой любви и никак иначе! А значит – за дело! И главное – ничего не перепутать…",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "300",
        "pdf":"https://drive.google.com/file/d/1ZKrrOIRldmF8629wYLak6jnDsEli0q1W/view?usp=drive_link"
      },
      {
        "id": "23",
        "name": "Звездная Кровь-2. Фригольд",
        "author": "Роман Прокофьев",
        "genre": "Боевая фантастика, Героическая фэнтези",
        "image": "./img/cat2_img26.jpg",
        "description":"Оказывается, это не Земля. И не другая планета. Все гораздо хуже: мы оказались в обитаемом Круге древней дайсон-сферы, которая уже шесть оборотов галактики находится на месте Солнечной системы. Здесь нет луны и звезд, а гигантские Игг-Древа заменяют солнце. Как это возможно? Никто не знает. Местные называют этот мир Единство и здесь царят суровые законы. Тут есть обычные люди и есть Восходящие, способные творить настоящие чудеса с помощью Скрижалей и Рун. Здесь есть Наблюдатели и наследие древней цивилизации Кел, есть небесные острова и таинственные Домены. Но самое важное здесь – Звездная Кровь!",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "450",
        "pdf":"https://drive.google.com/file/d/1Tlua-b8LiDj75RR5sd_QQ6qCrjADIvJu/view?usp=drive_link"
      },
      {
        "id": "24",
        "name": "Антидемон. Книга 3",
        "author": "Серж Винтеркей",
        "genre": "Боевое фэнтези, Книги про волшебников",
        "image": "./img/cat2_img27.jpg",
        "description":"Подготовка к будущей войне с высшими демонами идет полным ходом. Эйсон развернулся не на шутку, сколачивая команду соратников. Днем он усидчивый и прилежный студент, ночью – охотник на монстров, в том числе в человеческом обличье.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "400",
        "pdf":"https://drive.google.com/file/d/1Sc4nW9fh5DlDWh7gNpH10KWyoR97HaO1/view?usp=drive_link"
      },
      {
        "id": "25",
        "name": "Сам себе бренд. Искусство самопрезентации",
        "author": "Полина Крупышева",
        "genre": "Зарубежная деловая литература",
        "image": "./img/cat2_img28.jpg",
        "description":"Гарри Беквит является специалистом по маркетингу и основателем компании Beckwith Advertising and Marketing. Он читает лекции по маркетингу в университетах США и выступает на телевидении.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1000",
        "pdf":"https://drive.google.com/file/d/1PFLBablm5tqeXCT6WouCogQb6kOU7xWJ/view?usp=drive_link"
      },
      {
        "id": "26",
        "name": "Песнь теней",
        "author": "Никита Саидахмедов",
        "genre": "Боевое фэнтези, Книги про волшебников",
        "image": "./img/cat2_img29.jpg",
        "description":"В мире магии и тайн Люкас Скайвер, студент магии, отправляется на мстительное путешествие, исследуя темные культы и раскрывая страшные загадки. После неудачного столкновения с архиепископом темного бога, его тень превращается в сущность мести, Тень Отмщения. Силы Тени растут, и Люкас становится защитником света, стремясь разрушить защиту темного бога. Под влиянием древних духов и сил своего прошлого, Люкас и его наставник начинают освобождать свет, завершая свою эпическую борьбу с тьмой и магическими загадками.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "500",
        "pdf":"https://drive.google.com/file/d/1wbHXLkqp35zS9ubfIixclWA3jxV4cyFW/view?usp=drive_link"
      },
      {
        "id": "27",
        "name": "Город новых надежд",
        "author": "Анна Халин",
        "genre": "Зарубежное фэнтези, Книги для подростков",
        "image": "./img/cat2_img30.jpg",
        "description":"Девочка-подросток по имени Регина случайно обнаруживает у себя одну сверхспособность, после чего получает шанс развить и другие. Но чрезмерное усердие и жажда признания приводят к тому, что ей нужно найти альтернативный способ творить волшебство, ведь обычной девочкой она уже быть не хочет. Всё складывается удачно, Регина обнаруживает параллельный мир, полный чудес и пленяющий своей историей. Однако зло не дремлет и ищет пути подобраться к новоиспеченной супергероине...",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "950",
        "pdf":"https://drive.google.com/file/d/1MmK319xthLKY3662Suo6kFaaSnXXlhLL/view?usp=drive_link"
      },
      {
        "id": "28",
        "name": "Шут",
        "author": "Фрост Кей",
        "genre": "Героическое фэнтези, Зарубежная фантастика",
        "image": "./img/cat2_img31.jpg",
        "description":"Обманув короля, Тэмпест наконец обрела долгожданный приз: место в королевском совете. Но за все приходится платить свою цену. Король желает, чтобы она вернулась в Темный Двор к Шуту и подавила восстание. Оказавшись между долгом перед королевством и собственной совестью, Тэмпест полна решимости найти своих врагов.",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "600",
        "pdf":"https://drive.google.com/file/d/1mJbuAXroBWDHozlct8qQZK9fOTx5fkRl/view?usp=drive_link"
      },
      {
        "id": "29",
        "name": "Тенесвет. Дорога к неведомому",
        "author": "Дорит Медвед",
        "genre": "Боевое фэнтези, Героическое фэнтези",
        "image": "./img/cat2_img32.jpg",
        "description":"Решающая битва выиграна, а между Лунарией и Сатандрой наступил долгожданный мир. Но всё это не радует Тару, у которой война забрала самых близких ей людей. Чтобы отвлечь любимую от невеселых мыслей, Люсифер дарит ей увлекательное морское путешествие на галеоне «Скарлетт».",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "350",
        "pdf":"https://drive.google.com/file/d/1BRDzqMub5mcIB5Gnce2XDeqEquptmLQV/view?usp=drive_link"
      },
      {
        "id": "30",
        "name": "Говори с собой правильно",
        "author": "Ирина Медведева",
        "genre": "Нейропсихология, Саморазвитие",
        "image": "./img/cat2_img1.jpg",
        "description":"Наедине с собой бывает непросто… Удается ли вам справляться с внутренним критиком? Чувствуете ли вы опору внутри себя? Получается ли у вас сохранять уверенность в сложной ситуации? Умеете ли вы разрешать собственные сомнения? Удается ли вам доводить задуманное до конца?",
        "language": "Ru",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1000",
        "pdf":"https://drive.google.com/file/d/1AwSCXPxI8Kg87GgnFecCptP-VIHpZ5PF/view?usp=drive_link"
      },
      {
        "id": "31",
        "name": "Treasure Island",
        "author": "Robert Louis Stevenson",
        "genre": "Приключения",
        "image": "./img/cat2_img33.jpg",
        "description":"One day, a new guest settles in the inn. After a while, strange guests begin to come to him. One day Billy is visited by a blind beggar who hands him a black mark. Billy, having received the mark, decides to leave his place in a hurry, but suddenly dies. Jim and his mother, to whom Billy owes money for a stay, search the dead sailor and his belongings. They find money and a package of papers at the bottom of his trunk. From these papers it becomes clear that Bones was an assistant captain on the ship of the famous pirate Flint and owned a map of treasure island.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "750",
        "pdf":"https://drive.google.com/file/d/1dnyl7QcuS7EfwybrTeLnEin_8-5Q07hG/view?usp=drive_link"
      },
      {
        "id": "32",
        "name": "The Sun Also Rises",
        "author": "Ernest Hemingway",
        "genre": "Журналистика",
        "image": "./img/cat2_img34.jpg",
        "description":"American journalist Jake Barnes fought on the fronts of the First World War and was seriously injured. Barnes spends every night with friends in a bar on Boulevard Montparnasse, hoping that alcohol will help him heal the mental and physical wounds inflicted by the First World War. Barnes is in love with Bret Ashley, who embodies the new sexual freedom of the 1920s, and has numerous affairs. She is also in love with Barnes, however, due to Jake's injuries in the war, their romance is exclusively spiritual in nature.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "250",
        "pdf":"https://drive.google.com/file/d/1goJrMiHmspM6OiR36GhVV8Nl9X0Ce8CG/view?usp=drive_link"
      },
      {
        "id": "33",
        "name": "The Devil Wears Prada",
        "author": "lauren Weisberger",
        "genre": "Журналистика, Ужасы",
        "image": "./img/cat2_img35.jpg",
        "description":"Dreaming of becoming a journalist, a provincial girl, Andy, after graduating from university, gets a position as an assistant to the all-powerful Miranda Priestly, the despotic editor of one of the largest New York fashion magazines. Andy had always dreamed of such a job, not knowing what kind of nervous tension it would be associated with.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1400",
        "pdf":"https://drive.google.com/file/d/1WArvhiOjiXk91EB7nBE7KTf-D6Brv10L/view?usp=drive_link"
      },
      {
        "id": "34",
        "name": "The Hound of the Baskervilles",
        "author": "Arthur Conan Doyle",
        "genre": "Мифы, Расследования",
        "image": "./img/cat2_img36.jpg",
        "description":"The plot is based on the investigation of the death of Sir Charles Baskerville, who died under mysterious circumstances. The family legend of the devil dog that haunts all Baskervilles has been passed down from generation to generation in the Baskervilles family. Sherlock Holmes and Dr. Watson take over the investigation of this case. The time of action is September/October 1889. This was Holmes' first appearance since his supposed death in the work The Last Holmes Case. The success of this story contributed to the revival of the character.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1000",
        "pdf":"https://drive.google.com/file/d/1dG5ppJPaVuZ7Pltzba9GhxZOF0NGD17V/view?usp=drive_link"
      },
      {
        "id": "35",
        "name": "The Gun Seller",
        "author": "Yugh Laurie",
        "genre": "Биографии, Истории о жизни",
        "image": "./img/cat2_img37.jpg",
        "description":"Thomas Lang is a retired captain of the Scottish Guards Regiment, who earns his living by doing odd jobs like guarding various money bags. But when a stranger offers a murder order in Amsterdam, Thomas refuses for moral reasons. Moreover, he decides to warn the victim, businessman Alexander Wolf, about the impending assassination attempt",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "500",
        "pdf":"https://drive.google.com/file/d/1VjkPdhlVxqO-V4xdbIFgvPdH2qLvSLBr/view?usp=drive_link"
      },
      {
        "id": "36",
        "name": "Lullaby",
        "author": "Chuck Palahniuk",
        "genre": "Роман, Утопия",
        "image": "./img/cat2_img38.jpg",
        "description":"Lullaby is a utopia novel that tells about the darkest sides of the human soul, and how it can be difficult to come to your true self.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1900",
        "pdf":"https://drive.google.com/file/d/1qcL5yt8LKsA6RlZHIT13jCANP0dNfIg8/view?usp=drive_link"
      },
      {
        "id": "37",
        "name": "Life of Pi",
        "author": "Yann Martel",
        "genre": "Истории о жизни, Саморазвитие",
        "image": "./img/cat2_img39.jpg",
        "description":"This is the story of the son of the owner of an Indian zoo, a boy named Pi. He learns about the world, learns to defend his principles, seeks his own path to God, living according to the canons of three faiths, falls in love… But by the will of fate, his family is forced to emigrate. Halfway between India and Canada, the ship crashes, and Pi remains in the dinghy along with a Bengal tiger, a hyena, a zebra and an orangutan. There is a vast expanse of water around, and the unknown lies ahead.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "900",
        "pdf":"https://drive.google.com/file/d/1-OY2r6Y49CdVZpjEs4DthSLLMcMBigOG/view?usp=drive_link"
      },
      {
        "id": "38",
        "name": "Gone with the Wind",
        "author": "Margaret Mitchell",
        "genre": "Нейропсихология, Саморазвитие",
        "image": "./img/cat2_img40.jpg",
        "description":"The book tells about love against the background of the First World War. The novel is largely autobiographical - Hemingway served at the front in Italy, was wounded and lay in a hospital in Milan, where he had an affair with a nurse.The novel was released on June 30, 1936 and became one of the most famous bestsellers of American literature. By the end of 1936, more than one million copies had been sold. In the same year, Mitchell transferred the rights to the film adaptation of the novel and in 1939 a film of the same name was shot starring Vivien Leigh and Clark Gable.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1200",
        "pdf":"https://drive.google.com/file/d/1uK6PD4xDWYeki-tHK8BvyispPXrAIIkA/view?usp=drive_link"
      },
      {
        "id": "39",
        "name": "A Farewell to Arms",
        "author": "Ernest Hemingway",
        "genre": "Роман, Биография, Война",
        "image": "./img/cat2_img41.jpg",
        "description":"The book tells about love against the background of the First World War. The novel is largely autobiographical - Hemingway served at the front in Italy, was wounded and lay in a hospital in Milan, where he had an affair with a nurse.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "800",
        "pdf":"https://drive.google.com/file/d/16iOYuh-bhDKRcSRRjGmlp5gqD69vDS7n/view?usp=drive_link"
      },
      {
        "id": "40",
        "name": "Planescape: Torment. A Novelization",
        "author": "Stromberg Logan, Hess Riess",
        "genre": "Фэнтези",
        "image": "./img/cat2_img42.jpg",
        "description":"This really is a novelization, a lot of effort being made to go through the game as it's played, going way beyond merely describing and attempting to make events flow more naturally. There is a lot of added writing, and much of it is actually really, really good, greatly improving an already great story.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "800",
        "pdf":"https://drive.google.com/file/d/1wAYJdoCsF5iU4W5bQqOoyJ9dms6tsoO2/view?usp=drive_link"
      },
      {
        "id": "41",
        "name": "Esotericism and the Academy",
        "author": "Hanegraaff Wouter",
        "genre": "Религия",
        "image": "./img/cat2_img43.jpg",
        "description":"In this book the author makes no attempt to provide a map of the domain, or write its history. Instead, he writes the history of how scholars and intellectuals have imagined it, ever since the time that its contours first began to be drawn by those who claimed to know of its existence. It is only through their eyes that we will be introduced to it here, and it will quickly become apparent that many of those who have confidently described its nature – sometimes as a lost paradise, sometimes as a dark realm filled with demons, or a resort of fools – have been projecting their own hopes or fears onto it, or have just been repeating what others said about it. But no matter how extravagant the claims that have been made about this continent, one thing is clear: it has always been considered the domain of the Other.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "2000",
        "pdf":"https://drive.google.com/file/d/1G-70O4NrrAV-REGHAiZ0qfeHA0gozbTa/view?usp=drive_link"
      },
      {
        "id": "42",
        "name": "Inferno",
        "author": "Brown Dan",
        "genre": "Триллер",
        "image": "./img/cat2_img44.jpg",
        "description":"With these words echoing in his head, eminent Harvard symbologist Robert Langdon awakes in a hospital bed with no recollection of where he is or how he got there. Nor can he explain the origin of the macabre object that is found hidden in his belongings. A threat to his life will propel him and a young doctor, Sienna Brooks, into a breakneck chase across the city of Florence. Only Langdon’s knowledge of hidden passageways and ancient secrets that lie behind its historic facade can save them from the clutches of their unknown pursuers. With only a few lines from Dante’s dark and epic masterpiece, The Inferno, to guide them, they must decipher a sequence of codes buried deep within some of the most celebrated artefacts of the Renaissance — sculptures, paintings, buildings — to find the answers to a puzzle which may, or may not, help them save the world from a terrifying threat…",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "650",
        "pdf":"https://drive.google.com/file/d/1gpEOnOVt72IbNTHqqo67OoPzI8ZPHl5C/view?usp=drive_link"
      },
      {
        "id": "43",
        "name": "The Canterville Ghost and Other Stories",
        "author": "Oscar Wilde",
        "genre": "Рассказы",
        "image": "./img/cat2_img45.jpg",
        "description":"The story of the Canterville Ghost was of an old English country house, Canterville Chase, which has all the accoutrements of a traditional haunted house. Descriptions of the wainscoting, the library panelled in black oak, and the armour in the hallway characterize the Gothic setting. Wilde mixes the macabre with comedy, juxtaposing devices from traditional English ghost stories such as creaking floorboards, clanking chains, and ancient prophecies with symbols of contemporary American consumerism.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1100",
        "pdf":"https://drive.google.com/file/d/1mdnIYVEl-01du6P2qxVo2i8pfVJv1T2k/view?usp=drive_link"
      },
      {
        "id": "44",
        "name": "JXTA in a Nut shell",
        "author": "Oaks Scott, Traversat Bernard",
        "genre": "Программирование",
        "image": "./img/cat2_img46.jpg",
        "description":"Written by the key members of Sun Microsystem's Project JXTA,JXTA in a Nutshell is the definitive reference to the most solid platform yet for Peer-to-Peer distributed computing. P2P enables users with the same networking application to connect with each other and directly access files from one another's hard drives. JXTA is a giant step forward in the evolution of P2P. O'Reilly's pioneering reference is the first and last word on this powerful distributed computing technology. JXTA in a Nutshelldelivers all the information you need to get started, including an overview of P2P distributed computing, an explanation of the JXTA Project's new platform, and ways that developers can become a part of the development effort.JXTA in a Nutshell introduces major concepts in a hands-on way by explaining them in context to the shell, and contains a complete reference to the JXTA application bindings. Also included is the full JXTA protocol specification. The book covers important topics such as security, and how the JXTA technology fits into the standard Java classes.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1000",
        "pdf":"https://drive.google.com/file/d/1SqnVpoXUAzODrniy-lccS3uWmWYPid-k/view?usp=drive_link"
      },
      {
        "id": "45",
        "name": "Midnight Fae Academy",
        "author": "Foss Lexi C.",
        "genre": "Люовно-фантастические романы",
        "image": "./img/cat2_img47.jpg",
        "description":"Author Note: This is a dark paranormal reverse harem romance, and despite Aflora's opinions on the matter, there will definitely be biting. Shadow, aka Shade, guarantees it.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "700",
        "pdf":"https://drive.google.com/file/d/1yhqs_mXHXvk2hWJRy2kxyszAPc-chkGn/view?usp=drive_link"
      },
      {
        "id": "46",
        "name": "Leopardstar's Honor",
        "author": "Hunter Erin",
        "genre": "Фэнтези",
        "image": "./img/cat2_img48.jpg",
        "description":"Since her kithood, Leopardfur has believed that she would one day save RiverClan from destruction, a belief based on a prophetic dream her father once had before he became a medicine cat. Under Crookedstar’s leadership, she is proud to become first a strong warrior, then deputy, fighting fiercely to protect RiverClan’s territory from the encroachment of their enemies. But when the rise of Tigerstar shatters all semblance of peace among the Clans, Leopardstar, now leader, comes to make a decision she fears will be unforgivable. Determined to fulfill her destiny and lead RiverClan to greatness, Leopardfur must finally find the balance between maintaining peace among the Clans and protecting her own…",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "250",
        "pdf":"https://drive.google.com/file/d/1EdwmJeT4HSmdJVhP4VzJ0j4zWfAzsf3X/view?usp=drive_link"
      },
      {
        "id": "47",
        "name": "The Place of No Stars",
        "author": "Hunter Erin",
        "genre": "Исторические любовные романы",
        "image": "./img/cat2_img49.jpg",
        "description":"The time has come to enter the Dark Forest. ThunderClan's deputy, Squirrelflight, has vanished with the cat now known to be an impostor, and suspicion and mistrust now reign among the five Clans. They have learned the cause of their ancestors' mysterious silence—and with it, what they must do if they hope to bring light back to the darkness.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "650",
        "pdf":"https://drive.google.com/file/d/1mCzphs2EonvxJ3e55ifmuQA0rPQA46_d/view?usp=drive_link"
      },
      {
        "id": "48",
        "name": "Darkness Within",
        "author": "Hunter Erin",
        "genre": "Исторические любовные романы",
        "image": "./img/cat2_img50.jpg",
        "description":"Is the warrior code worth a warrior's life? Exiled after a battle that left all five Clans devastated, ThunderClan's loyal deputy, Squirrelflight, must bring to light an earth-shattering truth: the identity of the cat ruling ThunderClan while wearing Bramblestar's face. With tensions among the Clans at a breaking point, another battle looms, and even Squirrelflight may not be able to ensure Bramblestar has a body to return to. If he returns at all...",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1900",
        "pdf":"https://drive.google.com/file/d/19ZkyqEZscKeAXNDLAqwMa9rzOQxjrA8m/view?usp=drive_link"
      },
      {
        "id": "49",
        "name": "The curse of Slagfid",
        "author": "Boyer Elizabeth H.",
        "genre": "Фэнтези",
        "image": "./img/cat2_img51.jpg",
        "description":"Leifr and Thurid were in trouble - worse than usual. In Leifr's efforts to recover his lost love, Ljosa, and Thurid's attempt to escape the Inquisitors they had fallen into the hands of the evil Master Wizard Djofull. Djofull had tricked them into swearing in blood that they would destroy the curse that afflicted Hraedsla-dalur or return to serve his vile plans.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1900",
        "pdf":"https://drive.google.com/file/d/1uhEwlsM6zBPnaWppSox3r9ccIp-4lbZE/view?usp=drive_link"
      },
      {
        "id": "50",
        "name": "The Missing Coins",
        "author": "John Escott",
        "genre": "Детектив",
        "image": "./img/cat2_img52.jpg",
        "description":"British English Pete and Carla are students. One day they look at some very old coins and stamps in a shop. Pete wants to buy some stamps, but they are very expensive. Later that day some coins are missing from the shop and the shopkeeper wants to find Pete.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1750",
        "pdf":"https://drive.google.com/file/d/1m8GtHkUi8U1lqN_ewo3CX_2N6kEwSD1C/view?usp=drive_link"
      },
      {
        "id": "51",
        "name": "Hercules",
        "author": "Timothy Boggs",
        "genre": "Историческое фэнтези",
        "image": "./img/cat2_img53.jpg",
        "description":"When the Fire, the mighty sword of Hephaestus, falls into the hands of thugs determined to use its power against the innocent, Hercules is tasked by the gods to find and return the fearsome weapon to its owner. With time running short, Hercules must face an encampment of armed bandits ready to put his super-human strength to the test… but will he be able to return the Fire before Hephaestus’ anger erupts? Based on the hit television series created by Christian Williams, By the Sword continues the legendary journeys of Hercules — a hero who possesses a strength the world has never seen… a strength surpassed only by the power of his heart.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1600",
        "pdf":"https://drive.google.com/file/d/1a7lQFyQ8aHS7pBvbgkxWS0qtcZPPJZXP/view?usp=drive_link"
      },
      {
        "id": "52",
        "name": "The Piano",
        "author": "Rosemary Border",
        "genre": "Рассказ",
        "image": "./img/cat2_img54.jpg",
        "description":"One day, a farmer tells a farm boy to take everything out of an old building and throw it away. ‘It’s all rubbish,’ he says. ‘In the middle of all the rubbish, the boy finds a beautiful old piano. He has never played before, but now, when his fingers touch the piano, he begins to play. He closes his eyes and the music comes to him – and the music moves his fingers. When he opens his eyes again, he knows that his life is changed for ever…",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1700",
        "pdf":"https://drive.google.com/file/d/1xl2uYJrR2WxYJ6Mt9rdQd0O25K-PfKuT/view?usp=drive_link"
      },
      {
        "id": "53",
        "name": "New Yorkers Short Stories",
        "author": "O.Henry",
        "genre": "Короткие рассказы",
        "image": "./img/cat2_img55.jpg",
        "description":"A housewife, a tramp, a lawyer, a waitress, an actress — ordinary people living ordinary lives in New York at the beginning of this century. The city has changed greatly since that time, but its people are much the same. Some are rich, some are poor, some are happy, some are sad, some have found love, some are looking for love.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1000",
        "pdf":"https://drive.google.com/file/d/1CxTa_a_Sq85MkobCWJdC9w3XSLncroFf/view?usp=drive_link"
      },
      {
        "id": "54",
        "name": "Jungle Book",
        "author": "Rudyard Kipling",
        "genre": "Приключения",
        "image": "./img/cat2_img56.jpg",
        "description":"In the jungle of Southern India the Seeonee Wolf-Pack has a new cub. He is not a wolf — he is Mowgli, a human child, but he knows nothing of the world of men. He lives and hunts with his brothers the wolves. Baloo the bear and Bagheera the panther are his friends and teachers. And Shere Khan, the man-eating tiger, is his enemy.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "500",
        "pdf":"https://drive.google.com/file/d/1YOTLvZjFby_QEcJzZEwddaGYGfyX7bWk/view?usp=drive_link"
      },
      {
        "id": "55",
        "name": "The Adventures of Tom Sawyer",
        "author": "Mark Twein",
        "genre": "Приключения",
        "image": "./img/cat2_img57.jpg",
        "description":"In the first part, The Lord of the Rings, a shy young hobbit named Frodo Baggins inherits a simple gold ring that holds the secret to the survival — or enslavement of the entire world.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1800",
        "pdf":"https://drive.google.com/file/d/1r1gUvqxWIAI7V4sSD-qJr2Aq6ywmIcqB/view?usp=drive_link"
      },
      {
        "id": "56",
        "name": "The Fellowship of the Ring",
        "author": "J.R.R. Tolkien",
        "genre": "Фэнтези, Приключения",
        "image": "./img/cat2_img58.jpg",
        "description":"In the first part, The Lord of the Rings, a shy young hobbit named Frodo Baggins inherits a simple gold ring that holds the secret to the survival — or enslavement of the entire world.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "950",
        "pdf":"https://drive.google.com/file/d/1tq_JPUXtt_Hgs5OD_fhlRyykNVAVGSMO/view?usp=drive_link"
      },
      {
        "id": "57",
        "name": "The Da Vinci Code",
        "author": "Dan Brown",
        "genre": "Детекив, Роман-тайна",
        "image": "./img/cat2_img59.jpg",
        "description":"The Da Vinci Code is a 2003 mystery-detective novel written by Dan Brown. It follows symbologist Robert Langdon and cryptologist Sophie Neveu after a murder in the Louvre Museum in Paris, when they become involved in a battle between the Priory of Sion and Opus Dei over the possibility of Jesus having been married to Mary Magdalene. The title of the novel refers, among other things, to the finding of the first murder victim in the Grand Gallery of the Louvre, naked and posed like Leonardo da Vinci’s famous drawing, the Vitruvian Man, with a cryptic message written beside his body and a pentagram drawn on his chest in his own blood.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "250",
        "pdf":"https://drive.google.com/file/d/1VQlzLOeE14xbZ_9MuJSHw1p-q1pZNIUP/view?usp=drive_link"
      },
      {
        "id": "58",
        "name": "It",
        "author": "Stephen King",
        "genre": "Ужасы, Роман",
        "image": "./img/cat2_img60.jpg",
        "description":"«It» is a 1986 horror novel by American author Stephen King. The story follows the exploits of seven children as they are terrorized by the eponymous being, which exploits the fears and phobias of its victims in order to disguise itself while hunting its prey. «It» primarily appears in the form of a clown in order to attract its preferred prey of young children. The novel is told through narratives alternating between two time periods, and is largely told in the third-person omniscient mode.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1986",
        "pdf":"https://drive.google.com/file/d/195hB8dbKiAtkUsbqQWKvK_EoKY6jNEl0/view?usp=drive_link"
      },
      {
        "id": "59",
        "name": "Secret garden",
        "author": "F.H. Burnett",
        "genre": "Приключения, Расследования",
        "image": "./img/cat2_img61.jpg",
        "description":"Little Mary Lennox is a bad-tempered, disagreeable child. When her parents die in India, she is sent back to England to live with her uncle in a big, lonely, old house. There is nothing to do all day except walk in the gardens — and watch the robin flying over the high walls of the secret garden . . . which has been locked for ten years. And no one has the key.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "350",
        "pdf":"https://drive.google.com/file/d/19AKA0AB0JGjyuLpZhyP1lAbIrmdK1MvQ/view?usp=drive_link"
      },
      {
        "id": "60",
        "name": "Woman in black",
        "author": "Susan Hill",
        "genre": "Страшные истории",
        "image": "./img/cat2_img62.jpg",
        "description":"It is a Cristmas Eve now. The members of one family are telling horrible stories about ghosts. One of them Arthur Kipps listen all of them and has remember his own story. But he couldn’t tell about it for his family. So he decided to write it on the paper. Many years ago he was working at a law company. He was given the task to make order in papers of a dead woman. That woman was very strange. And place where he had to go was strange too. And people who lived there were very suspicious. Arthur was full of deadly determination to do his work and went to the empty house located among the bogs and nobody lived around of that place. The dead woman had hold all documents and letters for several decades, Arthur spent a lot of time to make order in it. But all time the woman in black prevented him of doing his work.",
        "language": "Eng",
        "free": "Нет",
        "read": "Нет",
        "upload": "Нет",
        "cost": "1900",
        "pdf":"https://drive.google.com/file/d/1tVZaDR1M4LUmM-aJ1U2Rex_IemJarog2/view?usp=drive_link"
      }
  ];

  // Save booksData to local storage
  localStorage.setItem('books', JSON.stringify(booksData));

  let searchInput = document.getElementById('search_input');
  let searchResults = document.getElementById('search_results');

  searchInput.addEventListener('input', (e) => {
    let searchTerm = e.target.value.toLowerCase();
    let results = booksData.filter((book) => {
      let title = book.name.toLowerCase();
      let author = book.author.toLowerCase();
      return title.includes(searchTerm) || author.includes(searchTerm);
    });

    if (searchTerm.length === 0) {
      searchResults.innerHTML = '';
      searchResults.style.display = 'none';
    } else {
      if (results.length > 0) {
        searchResults.innerHTML = '';
        results.slice(0, 3).forEach((book) => {
          let resultItem = document.createElement('div');
          resultItem.textContent = `${book.name} от автора ${book.author}`;
          resultItem.dataset.bookId = book.id;
          searchResults.appendChild(resultItem);
        });
        searchResults.style.display = 'block';
      } else {
        searchResults.innerHTML = '';
        let noResults = document.createElement('div');
        noResults.textContent = 'Совпадения не найдены';
        searchResults.appendChild(noResults);
        searchResults.style.display = 'block';
      }
    }
  });

  searchResults.addEventListener('click', (e) => {
    if (e.target.tagName === 'DIV') {
      let bookId = e.target.dataset.bookId;
      window.location.href = `/purchase/index.html?id=${bookId}`;
    }
  });

  booksData.forEach((book) => {
    delete book.pdf; // remove the pdf property
  });
});